name: Compile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        cygwin: 1

    - name: Compile C++ code
      run: |
        g++ -o bunnymodXT_Injector.exe src/main.cpp

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: bunnymodXT_Injector.exe
